import{initializeApp}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import{getAuth,GoogleAuthProvider,signInWithPopup,signInWithRedirect,getRedirectResult,signOut,onAuthStateChanged}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
import{getFirestore,collection,doc,getDoc,setDoc,addDoc,updateDoc,deleteDoc,onSnapshot,query,orderBy,serverTimestamp,writeBatch}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
const CONFIG={apiKey:'AIzaSyCnQ9wljW0ujeneUUJO_K0cF6QsBB998tg',authDomain:'one-social-run.firebaseapp.com',projectId:'one-social-run',storageBucket:'one-social-run.firebasestorage.app',messagingSenderId:'629123641856',appId:'1:629123641856:web:b624e49745c58d66aadee5',measurementId:'G-GRSGNVXYB0'},ADMIN='jesussoler2003@gmail.com',app=initializeApp(CONFIG),auth=getAuth(app),db=getFirestore(app),provider=new GoogleAuthProvider(),$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let currentUser=null,isAdmin=false,events=[],gallery=[],attendees=[],activeEvent=null;
const safe=v=>{const d=document.createElement('div');d.textContent=v||'';return d.innerHTML},notify=t=>{const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2500)},dateText=s=>new Intl.DateTimeFormat('es-ES',{weekday:'long',day:'numeric',month:'long'}).format(new Date(s+'T12:00:00')),shortName=n=>{const a=(n||'Runner').trim().split(/\s+/);return a[0]+(a[1]?` ${a[1][0]}.`:'')};
async function login(){try{await signInWithPopup(auth,provider)}catch(e){if(e.code?.includes('popup'))await signInWithRedirect(auth,provider);else{console.error(e);notify('No se pudo iniciar sesión')}}}getRedirectResult(auth).catch(console.error);
$$('.js-auth').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();currentUser?signOut(auth):login()}));
document.addEventListener('click',async e=>{const b=e.target.closest('.js-join');if(!b)return;e.preventDefault();e.stopImmediatePropagation();if(!currentUser){notify('Entra con Google para apuntarte');await login();return}if(!activeEvent){notify('No hay una quedada abierta');return}const ref=doc(db,'events',activeEvent.id,'attendees',currentUser.uid),mine=attendees.find(a=>a.id===currentUser.uid);if(mine){if(confirm('¿Quieres desapuntarte de esta quedada?'))await deleteDoc(ref)}else{const companions=Math.max(0,Number(prompt('¿Cuántos acompañantes llevas? Escribe 0 si vienes solo.','0'))||0);await setDoc(ref,{uid:currentUser.uid,name:currentUser.displayName||'Runner',companions,createdAt:serverTimestamp()});notify('Ya estás apuntado')}} ,true);
onAuthStateChanged(auth,async u=>{currentUser=u;isAdmin=u?.email?.toLowerCase()===ADMIN;$$('.js-auth').forEach(b=>b.textContent=u?(isAdmin?'Administrador':'Salir'):'Entrar con Google');$('#adminFab')?.classList.toggle('show',isAdmin);if(u)await setDoc(doc(db,'users',u.uid),{name:u.displayName||'',email:u.email||'',photoURL:u.photoURL||'',lastLogin:serverTimestamp()},{merge:true});renderJoin();renderAdminPeople()});
onSnapshot(query(collection(db,'events'),orderBy('date','desc')),s=>{events=s.docs.map(d=>({id:d.id,...d.data()}));activeEvent=events.find(e=>e.active&&!e.archived)||events.find(e=>!e.archived)||null;watchAttendees();renderEvents();renderAdminEvents()},e=>{console.error(e);notify('Revisa las reglas de Firestore')});
let stopAttendees=()=>{};function watchAttendees(){stopAttendees();attendees=[];if(!activeEvent){renderJoin();return}stopAttendees=onSnapshot(collection(db,'events',activeEvent.id,'attendees'),s=>{attendees=s.docs.map(d=>({id:d.id,...d.data()}));renderJoin();renderAdminPeople()})}
onSnapshot(query(collection(db,'gallery'),orderBy('createdAt','desc')),s=>{gallery=s.docs.map(d=>({id:d.id,...d.data()}));renderGallery();renderAdminGallery()});
function renderEvents(){if(activeEvent){const sec=$('#proxima'),vals=sec.querySelectorAll('.event-info strong');sec.querySelector('.section-head p').textContent=activeEvent.description||'';sec.querySelector('.poster img').src=activeEvent.cover||'assets/run-poster.png';sec.querySelector('.event-card h3').innerHTML=dateText(activeEvent.date).replace(' de ','<br>');[activeEvent.time,activeEvent.distance,activeEvent.place,activeEvent.pace].forEach((v,i)=>{if(vals[i])vals[i].textContent=v});let map=$('#mapLink');if(!map){map=document.createElement('a');map.id='mapLink';map.className='sign-note';map.target='_blank';map.rel='noopener';sec.querySelector('.event-info').after(map)}map.textContent='Abrir ubicación ↗';map.href=activeEvent.mapUrl||'#';map.style.display=activeEvent.mapUrl?'inline':'none'}const past=events.filter(e=>e.archived||!e.active);$('#pastEvents').innerHTML=past.length?past.map(e=>`<article class="past-event"><span class="kicker" style="color:var(--blue)">${safe(e.date)}</span><h3>${safe(e.title)}</h3><p>${safe(e.place)} · ${safe(e.distance)}</p></article>`).join(''):'<p class="muted">Todavía no hay quedadas archivadas.</p>'}
function renderJoin(){const card=$('#proxima .event-card'),att=card.querySelector('.attendees');if(!$('#faces'))att.querySelector('.faces').id='faces';if(!$('#attendeeList')){const x=document.createElement('div');x.id='attendeeList';x.className='attendee-list';att.after(x)}if(!$('#joinHint')){const x=document.createElement('p');x.id='joinHint';x.className='sign-note';card.querySelector('.event-actions').after(x)}const people=attendees.reduce((n,a)=>n+1+(a.companions||0),0);$('#countText').textContent=people?`${people} personas apuntadas`:'Sé la primera persona en apuntarte';$('#faces').innerHTML=attendees.slice(0,3).map(a=>`<i class="face">${safe((a.name||'R').split(' ').map(x=>x[0]).slice(0,2).join(''))}</i>`).join('');$('#attendeeList').innerHTML=attendees.map(a=>`<span class="person-pill">${safe(shortName(a.name))}${a.companions?` +${a.companions}`:''}</span>`).join('');const mine=attendees.some(a=>a.id===currentUser?.uid);$$('.js-join').forEach(b=>b.innerHTML=mine?'<span>✓</span> Apuntado':'<span>✓</span> Me apunto');$('#joinHint').textContent=currentUser?(mine?'Pulsa de nuevo para desapuntarte.':'Tu correo solo es visible para el administrador.'):'Entra con Google para apuntarte.'}
function renderGallery(){let box=$('#publicGallery');if(!box){box=$('#galeria .gallery');box.id='publicGallery'}if(!gallery.length)return;box.innerHTML=gallery.map(g=>`<figure class="shot"><img src="${safe(g.url)}" alt="${safe(g.caption)}" loading="lazy"><figcaption class="caption"><strong>${safe(g.caption)}</strong></figcaption></figure>`).join('')}
$('#adminFab').onclick=()=>$('#adminDialog').showModal();$('#closeAdmin').onclick=()=>$('#adminDialog').close();$$('[data-admin-tab]').forEach(b=>b.onclick=()=>{$$('[data-admin-tab]').forEach(x=>x.classList.toggle('active',x===b));$$('.admin-pane').forEach(x=>x.classList.toggle('active',x.id===`admin-${b.dataset.adminTab}`))});
$('#eventForm').onsubmit=async e=>{e.preventDefault();if(!isAdmin)return;const id=$('#editEventId').value,data={title:$('#eventTitleInput').value.trim(),date:$('#eventDateInput').value,time:$('#eventTimeInput').value,distance:$('#eventDistanceInput').value.trim(),pace:$('#eventPaceInput').value.trim(),place:$('#eventPlaceInput').value.trim(),mapUrl:$('#eventMapInput').value.trim(),cover:$('#eventCoverInput').value.trim(),description:$('#eventDescriptionInput').value.trim(),active:$('#eventActiveInput').checked,archived:false,updatedAt:serverTimestamp()};if(data.active){const batch=writeBatch(db);events.filter(x=>x.active&&x.id!==id).forEach(x=>batch.update(doc(db,'events',x.id),{active:false}));await batch.commit()}if(id)await updateDoc(doc(db,'events',id),data);else await addDoc(collection(db,'events'),{...data,createdAt:serverTimestamp()});clearEvent();notify('Quedada guardada')};
function clearEvent(){$('#eventForm').reset();$('#editEventId').value='';$('#eventDistanceInput').value='5 km';$('#eventPaceInput').value='Tranquilo';$('#eventCoverInput').value='assets/run-poster.png';$('#eventActiveInput').checked=true}$('#clearEventForm').onclick=clearEvent;
function renderAdminEvents(){if(!$('#adminEventList'))return;$('#adminEventList').innerHTML=events.map(e=>`<div class="admin-event"><div><strong>${safe(e.title)}</strong><small>${safe(e.date)} · ${e.active?'Activa':e.archived?'Finalizada':'Borrador'}</small></div><div class="admin-actions"><button data-edit-event="${e.id}">Editar</button><button data-archive-event="${e.id}">${e.archived?'Reabrir':'Finalizar'}</button><button data-delete-event="${e.id}">Eliminar</button></div></div>`).join('')}
$('#adminEventList').onclick=async e=>{if(!isAdmin)return;const edit=e.target.dataset.editEvent,archive=e.target.dataset.archiveEvent,del=e.target.dataset.deleteEvent;if(edit){const x=events.find(y=>y.id===edit);$('#editEventId').value=x.id;for(const[k,id]of Object.entries({title:'eventTitleInput',date:'eventDateInput',time:'eventTimeInput',distance:'eventDistanceInput',pace:'eventPaceInput',place:'eventPlaceInput',mapUrl:'eventMapInput',cover:'eventCoverInput',description:'eventDescriptionInput'}))$('#'+id).value=x[k]||'';$('#eventActiveInput').checked=!!x.active;$('#adminDialog').scrollTop=0}if(archive){const x=events.find(y=>y.id===archive);await updateDoc(doc(db,'events',archive),{archived:!x.archived,active:false})}if(del&&confirm('¿Eliminar la quedada y sus datos visibles?'))await deleteDoc(doc(db,'events',del))};
$('#galleryForm').onsubmit=async e=>{e.preventDefault();if(!isAdmin)return;await addDoc(collection(db,'gallery'),{url:$('#galleryUrl').value.trim(),caption:$('#galleryCaption').value.trim(),createdAt:serverTimestamp()});e.target.reset();notify('Foto añadida')};function renderAdminGallery(){if(!$('#adminGalleryList'))return;$('#adminGalleryList').innerHTML=gallery.map(g=>`<div class="admin-event"><div><strong>${safe(g.caption)}</strong><small>${safe(g.url)}</small></div><button data-delete-gallery="${g.id}">Eliminar</button></div>`).join('')}$('#adminGalleryList').onclick=async e=>{if(e.target.dataset.deleteGallery&&isAdmin&&confirm('¿Quitar esta foto de la galería?'))await deleteDoc(doc(db,'gallery',e.target.dataset.deleteGallery))};
function renderAdminPeople(){if(!$('#adminPeopleList'))return;$('#adminPeopleList').innerHTML=attendees.length?attendees.map(a=>`<div class="admin-event"><div><strong>${safe(a.name)}</strong><small>${safe(a.email)} · ${a.companions||0} acompañantes</small></div><button data-remove-attendee="${a.id}">Quitar</button></div>`).join(''):'<p class="muted">Todavía no se ha apuntado nadie.</p>'}$('#adminPeopleList').onclick=async e=>{if(e.target.dataset.removeAttendee&&isAdmin&&activeEvent&&confirm('¿Quitar esta inscripción?'))await deleteDoc(doc(db,'events',activeEvent.id,'attendees',e.target.dataset.removeAttendee))};
$('#shareBtn').onclick=async()=>{const x={title:activeEvent?.title||'One Social Run',text:'¿Te vienes a la próxima quedada de One Social Run?',url:location.href};if(navigator.share)await navigator.share(x);else{await navigator.clipboard.writeText(location.href);notify('Enlace copiado')}};
